#!/bin/sh

set -eu

set --
set -- "$@" -smp "${VM_CPU:?}" -m "${VM_RAM:?}"
set -- "$@" -serial stdio -monitor unix:/run/qemu-monitor,server,nowait -device VGA -display vnc=:0
set -- "$@" -drive file=/var/lib/qemu/reactos.qcow2,index=0,media=disk,format=qcow2
set -- "$@" -netdev user,id=n0,"${VM_NET_OPTIONS?}"
set -- "$@" -device e1000,netdev=n0
set -- "$@" -usb -device usb-tablet
set -- "$@" -k "${VM_KEYBOARD:?}"

if [ "${VM_KVM:?}" = true ] && [ -c /dev/kvm ]; then
	set -- "$@" -accel kvm
else
	set -- "$@" -accel tcg
fi

cd /var/lib/qemu/
exec 2>&1
exec /usr/bin/qemu-system-x86_64 "$@"
